rikudou_json_api.router:
  path: '%rikudou_api.api_prefix%/{resourceName}/{id}'
  controller: Rikudou\JsonApiBundle\Controller\ApiRouter::router
  defaults:
    id: ~

rikudou_json_api.home:
  path: '%rikudou_api.api_prefix%'
  controller: Rikudou\JsonApiBundle\Controller\ApiRouter::home
