services:
  rikudou_api.internal.english_inflector:
    class: Symfony\Component\String\Inflector\EnglishInflector

  rikudou_api.inflector:
    class: Rikudou\JsonApiBundle\Service\Inflector
    arguments:
      - '@rikudou_api.internal.english_inflector'

  rikudou_api.name_resolution.camel_case:
    class: Rikudou\JsonApiBundle\NameResolution\CamelCaseApiNameResolution
    arguments:
      - '@rikudou_api.inflector'

  rikudou_api.name_resolution.kebab_case:
    class: Rikudou\JsonApiBundle\NameResolution\KebabCaseApiNameResolution
    arguments:
      - '@rikudou_api.inflector'
      - '@rikudou_api.name_resolution.camel_case'

  rikudou_api.cache.clear:
    class: Rikudou\JsonApiBundle\Service\Cache\CacheClearHook
    arguments:
      - '%rikudou_api.clear_cache_hook%'
      - '@cache.api_annotations'
    tags:
      - kernel.cache_clearer

  rikudou_api.query_builder.default:
    class: Rikudou\JsonApiBundle\Service\Filter\DefaultFilteredQueryBuilder
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@rikudou_api.object_parser.property_parser'

  rikudou_api.controller.api_router:
    class: Rikudou\JsonApiBundle\Controller\ApiRouter
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    tags:
      - controller.service_arguments
      - container.service_subscriber

  rikudou_api.listener.json_api_response:
    class: Rikudou\JsonApiBundle\Listener\JsonApiStructureResponseListener
    tags:
      - kernel.event_subscriber

  rikudou_api.listener.exceptions:
    class: Rikudou\JsonApiBundle\Listener\JsonApiErrorExceptionListener
    arguments:
      - '%rikudou_api.handle_special_exceptions%'
    tags:
      - kernel.event_subscriber

  rikudou_api.object_parser.parser:
    class: Rikudou\JsonApiBundle\Service\ObjectParser\ApiObjectParser
    arguments:
      - '@rikudou_api.object_parser.property_parser'
      - '@rikudou_api.object_parser.validator'
      - '@rikudou_api.object_parser.cache'
      - '@rikudou_api.name_resolution.camel_case'
      - '@rikudou_api.api_normalizer_locator'
      - '@doctrine.orm.entity_manager'
      - '@rikudou_api.inflector'
    calls:
      - method: setApiResourceLocator
        arguments:
          - '@rikudou_api.api_resource_locator'

  rikudou_api.object_parser.property_parser:
    class: Rikudou\JsonApiBundle\Service\ObjectParser\ApiPropertyParser
    arguments:
      - '@rikudou_api.object_parser.validator'
      - '@service_container'
      - '@rikudou_api.object_parser.cache'
      - '@Rikudou\JsonApiBundle\NameResolution\ApiNameResolutionInterface'
    tags:
      - container.service_subscriber

  rikudou_api.object_parser.cache:
    class: Rikudou\JsonApiBundle\Service\ObjectParser\ApiParserCache
    arguments:
      - '@cache.api_annotations'
      - '@rikudou_api.object_parser.validator'
      - '%rikudou_api.property_cache_enabled%'

  rikudou_api.object_parser.validator:
    class: Rikudou\JsonApiBundle\Service\ObjectParser\ApiObjectValidator
    arguments:
      - '@service_container'
    tags:
      - container.service_subscriber

  rikudou_api.api_resource_locator:
    class: Rikudou\JsonApiBundle\Service\ApiResourceLocator
    arguments:
      - '@rikudou_api.object_parser.parser'
      - '%rikudou_api.allow_resource_overwrite%'

  rikudou_api.api_normalizer_locator:
    class: Rikudou\JsonApiBundle\Service\ApiNormalizerLocator

  rikudou_api.api_normalizer.datetime:
    class: Rikudou\JsonApiBundle\Service\ObjectParser\Normalizer\DateTimeNormalizer
    arguments:
      - '%rikudou_api.transform_datetime_objects%'
      - '%rikudou_api.datetime_format%'
    tags:
      - rikudou_api.api_normalizer

  rikudou_api.command.install_routes:
    class: Rikudou\JsonApiBundle\Command\InstallRoutesCommand
    arguments:
      $projectDir: '%kernel.project_dir%'
    tags:
      - { name: console.command, command: 'json-api:install-routes' }
